version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./philosophy_exam
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
#    volumes:
#      - ./mysite/:/usr/src/mysite/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
#    env_file:
#      - ./.env.dev
    env_file:
      - ./.env.prod.db
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:12.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_volume: