# Generated by Django 3.2.11 on 2022-05-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedphilosopher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lections',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
